services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: dorsh97/wog
    container_name: wog-container
    ports:
      - "5000:5000"
    volumes:
      - ./Scores.txt:/app/Scores.txt
